services:
  api:
    image: estoque_api
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gyud!1608
      POSTGRES_DB: estoque_api